#!/usr/bin/env bash
# Replace port 8080 with port 80 in the Nginx configuration
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Restart the Nginx service and suppress output
service nginx restart > /dev/null 2>&1

# Check if Nginx is running
if service nginx status | grep -q "not running"; then
    echo " * nginx is not running"
else
    echo "Nginx is running"
fi
